version: '3'

services:
  laravel-app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx:rw
    networks:
      - app-network

  mysql-app:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravel
    networks:
      - app-network

networks:
  app-network:
    driver: bridge